spring.application.name=AndroidProyectApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/android_proyect
spring.datasource.username=postgres
spring.datasource.password=adsoft
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
